// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Luxon = require("luxon");

console.log(Luxon.DateTime.local(2017, 5, 15, 8, 30, undefined, undefined));

var dateObj = {
  year: 2017,
  month: 10,
  day: 2,
  hour: 3,
  minute: 1,
  second: 0,
  millisecond: 0
};

console.log(Luxon.DateTime.fromObject(dateObj).toISODate());

console.log(Luxon.DateTime.fromObject(dateObj).day);

console.log(Luxon.DateTime.DATETIME_FULL);

console.log(Luxon.DateTime.local(undefined, undefined, undefined, undefined, undefined, undefined, undefined).setZone("America/New_York").minus({
              weeks: 1
            }).endOf("day").toISO());

exports.dateObj = dateObj;
/*  Not a pure module */
