// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Jest  = require("@glennsl/bs-jest/src/jest.js");
var Luxon = require("luxon");

function getDateObject(dt) {
  return {
          year: dt.year,
          month: dt.month,
          day: dt.day,
          hour: dt.hour,
          minute: dt.minute,
          second: dt.second,
          millisecond: dt.millisecond
        };
}

Jest.test("to work", (function () {
        var now = Luxon.DateTime.local(undefined, undefined, undefined, undefined, undefined, undefined, undefined);
        return Jest.ExpectJs[/* toBe */2](new Date().getDate(), Jest.ExpectJs[/* expect */0](now.toJSDate().getDate()));
      }));

Jest.test("DateTime.local(2017) is the beginning of the year", (function () {
        var dt = Luxon.DateTime.local(2017, undefined, undefined, undefined, undefined, undefined, undefined);
        return Jest.ExpectJs[/* toEqual */12]({
                    year: 2017,
                    month: 1,
                    day: 1,
                    hour: 0,
                    minute: 0,
                    second: 0,
                    millisecond: 0
                  }, Jest.ExpectJs[/* expect */0](getDateObject(dt)));
      }));

exports.getDateObject = getDateObject;
/*  Not a pure module */
