// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Jest  = require("@glennsl/bs-jest/src/jest.js");
var Luxon = require("luxon");

Jest.test("to work", (function () {
        var now = Luxon.DateTime.local(undefined, undefined, undefined, undefined, undefined, undefined, undefined);
        return Jest.ExpectJs[/* toEqual */12](new Date().getDate(), Jest.ExpectJs[/* expect */0](now.toJSDate().getDate()));
      }));

/*  Not a pure module */
