// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Luxon = require("luxon");

console.log(Luxon.DateTime.local(2017, 5, 15, 8, 30, 0, 0));

var dateObj = {
  year: 2017
};

console.log(Luxon.DateTime.fromObject(dateObj).toISODate());

console.log(Luxon.DateTime.fromObject(dateObj).day);

console.log(Luxon.DateTime.DATETIME_FULL);

exports.dateObj = dateObj;
/*  Not a pure module */
